language: groovy

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "XabE5vlRY6yV5JvKgg3z6U08yDe5uGEBiNO/mJE7KpfLkm6Qf2E2G9A4n69gvs9Gydx1I4FMH5+zxTh3EZqKDI7MGuay7FZ1Qh0FJQJUYWMiBbp2+zIFnZQDTq74IWIzo0tXzcMjnq/MAz2gbQFETu8ejy9jnqqBwvZfhXXUX8FV+0lWTJtNZPiZGyzg3R2rcc2NW8LpvFQQtbBPH4xZYMPw/8tBT43tCp0lYGwsljqNod9hvuv5wsK+VYPe7rVzenuqIGd1QSHnVf2CBkVJOhB2tjwUHBKE+o4t5jwR5KIthyKjIcQh4N9Jq+tScQbCUlXIMc1MqdXkrMyfkhpldRlJtNv7gdNoRyPd4nMTnSQYwGhhe9CJt/luMQbU6JlBMDZrOyOCW7CONuuRI/s7REalGDKfdBWQ3D/TEdi+902pgGJMKHCugv0w5bXs1fA88PtW/vZ/MlOQcA+ynXt5nsTDTESfYMXbiW+Pwd4kYTRGaVCg+6Ih1CaiQtLb2oYBsIyUQ8zj4nHeoaTxOWRIQZFIQRUF1GswQGu/3H+7cQZT38cHRHlYC7Y5AWbFrfEU6ej6av/SKkuEJEwNoURjppot9oaRa+B3otmofdh7iR+mqDt6WAoLUNhsDu/pHKDYAuEuxr/9lXvsT3B1lNghbnnoHhEoQEECVkEz1tJ1gpA="

addons:
  coverity_scan:
    project:
      name: ScottG489/unified-diff-parser
    notification_email: scottg489@gmail.com
    build_command: ./gradlew build
    branch_pattern: master

after_success:
- ./gradlew cobertura coveralls
