language: groovy

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "XVAOWa0b4FW/eNodGYIA2UeCCDjPZnNbSr+OulPROhzZLhfG8kmV82NCn3kbdpj1ueaZOOCOKiIurMJh8vow305PUoO/ecS3kCkz3KlDbZrkHf8dJRxvWalE1Yh4FwqqAKauYGOG5P4rBoE9KzxHdJt6Nq6PP2PJuoAghWfqW/xxORoa2uDn4RK9MNf56C+AadhYAKjVutzrcHe029Yg8qnkjWkKyQ2/wH8DICBpEisLhOy3Eh87bs36EKdXLMVCj5cJ452fn/2pH2d7rO33VbZJJwQr1pX/yeG8kPonpx5F/fNjq86akUgknaWoWQfUtITyuqEKVbCJZ87Zsz2sw/c74Wf48FxTyJ1YGaZiK+K6uRxYKEOqnVe7FjT9GBr+UwFdPnMuyci8TOHM37XHm+L2bFqji3ASSalLjsOWT9y+imWiHc50saLfaxVxT9hID7arE2kYqXzLGfUjwTeQa5FB4uKHsA32XAG8451VlmU+J8owOSKQuRZHQpBa6LOLAOU3ZMBMdaL+Do4xGYgciwc2V1jrRBXOWdrRQnnua1/UT0flcKN/nGTJEnx3NgHOxvOjfAFaVuzrUZmotW9IsNPeoxs0m7WHLF/w7ga/Tr5p3V8g+wagS4Ty/en5zkDjyAKTmBgQp2jXf1hsQ6ki5xSrDcoSUp71CdHevEY9vlA="

addons:
  coverity_scan:
    project:
      name: ScottG489/unified-diff-parser
    build_command: ./gradlew build
    branch_pattern: master

after_success:
- ./gradlew cobertura coveralls
